### PR TITLE
tune elasticsearch for allinone setup

### PR DESCRIPTION
**Pull request by aschaber1**
the documentation suggests these settings for a single node setup.
http://docs.graylog.org/en/2.1/pages/installation/manual_setup.html?highlight=elasticsearch_#configuration

### CODE REVIEW

**Comment by joschi** [comment]
@aschaber1 Why exactly would you change these (default) settings? What's your use case?

**Comment by aschaber1** [comment]
sorry my bad, didn't drop the number of shards to 1.
the setting the number of replicas to 0 (as per default) is questionable.

**Comment by joschi** [comment]
@aschaber1 Okay, but **why** would you change these settings?

**Comment by bernd** [comment]
Closing this due to inactivity. Please re-open if you have feedback. Thank you!

**Pull request closed without merging**
